[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.10"

[[override]]
  version = "kubernetes-1.13.10"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.13.10"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  name = "k8s.io/go-client"
  version = "kubernetes-1.13.10"

[[override]]
  branch = "master"
  name = "golang.org/x/net"
